defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  - profile_images

url: "" 
baseurl: ""

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-github-metadata
